### PR TITLE
Add "Ontology" as dataType

### PR DESCRIPTION
**Pull request by rabuono**
Exchanged `Controlled Vocabulary` for `Ontology` as `dataType` for Attributes that have ontology terms as expected values.
Also commented out regex from `dataType` and substitute it with `"String"` in `sample_collection_plant_v1.0.0.json`.

### CODE REVIEW

**Comment by floradanna** [comment]
On principle, I agree. However, this means to add "Ontology" as attribute type in SEEK. What are the consequences of this?
- how to define the difference between CV and Ontology in SEEK? Maybe, just a list of terms vs URI/URL?
- what if each terms in CV has an ID/URL?
- currently, the interface to make CV in SEEK includes the option for ontology. Shall we address that? Is this an issue?

**Comment by rabuono** [comment]
I understood that `Ontology` had already been introduced as an Attribute Type in SEEK. So this change would just be a correction to conform to the current state.

In my understanding, Ontology terms would need to come from a registered Ontology that can be found in OLS. Also, have an assigned URI. But I don't know what, if any, validations are currently applied.

**Comment by floradanna** [comment]
@vdkkia does the attribute type "Ontology" already exist in SEEK?

**Comment by vdkkia** [comment]
@floradanna It does not exist in Seek, but I have added it in the template branch.

**Comment by floradanna** [comment]
I am a bit worried about the GUI. Currently, there is only 1 GUI to choose CV/Ontology in SEEK and it is linked to attribute type "CV". Are we going to duplicate that GUI for attribute type "Ontology"? Or do we delete the possibility to choose Ontology from the GUI linked to attribute type "CV"? Shall we discuss with other developers?

**Comment by rabuono** [comment]
From discussion about differentiating CV and Ontology lists:

In the future a separation of the GUI for making a CV list and an Ontology list.
- An Ontology list must have all terms with IRI. Ontology terms can be fetched 
  - In an Ontology Attribute Type, the ontology list is a suggestion. In addition to the ontology terms, the User is allowed to add free text as a value. 

- A CV list must have at least one term without IRI. All other terms may have IRIs (i.e. they come from an ontology). Ontology terms in a CV list are not fetched from OLS, but added manually by the User.
  - In a CV Attribute Type, the CV list is enforced. No free text is allowed as a value.

**Pull request merged**
